language: node_js
node_js:
- 8
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn run build
- cd dist && zip -r release.zip .
before_deploy:
- pwd && ls
deploy:
  provider: releases
  api_key:
    secure: "sn/In7Zxn6Izn5ZPZ+0Fggym+Eqjp4YP4vYUzc4GssiKd9gtinALpG3JtxccEN7tlaE4X4mjpHm/9PivjLOGKcH7wy8wUjKBhot+DgQGNqtP+AGOsevNtV6Y6gwgMFdlniyxiPJ6InY5sG1/8mN9UzsDXfVcuMpOO5QuXw034tWLuPgKieSoFu1cwBweJFzaksTn2MiGJLAgOA0f4sxYWFrgRN5URpUQ1Ugvdmn6FFyPnHjFKcIOK+Yu1+oEDBJSxtNNtpHlCV0qxw9XzH72tqRYlr6S6qn/e4MB9BFavyX4hD3FImK72Q0/eC0g6/ytils1ihk6HlEN1ODdG9xCkxHTOl+Iwhzo4XB6k8zdvkZhNSaUEQRjqR24fXpZggtkUFAui4+U7nPrsmW2XdSorRkXIoY44MjBm7zzGrZp1yJFO1b0LDsz2Oislc2fNQnDr6oZviVipFy0qqAiYt5IuDKF2JKxTFgtKC3NW4Wozzfa6m6pCRvlrT5SuKowV05it+goyB9VWcQ9quuuEbGEqBGyD0x6Aegeth3LeMfv96RVjBblaVIpVRzvWYzaLKNfXO8D85+r/v//FC4lYD1gxIGoM8o68DLu/lzqNphikvqI8/V4/qcYzZM/+N2Ec+PnkOA+XxDyaJagSp+OvoOnevKbIP6TlaxJrISa6U2vMn0="
  file: release.zip
  skip_cleanup: true
  on:
    tags: true
